# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9ee18224ccfd55af38c24ec5e5491b8e7ed0a30bf5af25b9877549dfd576c233f33e66fbbc4847359b7d723d969d7c9b0f0990f03ddf1de4b17c408defa8a7ae

test:
  secret_key_base: af8ac3b4ae60c3f6071c2f3936fbed756b94212b3821f0b40ed5d346967ac340884f774042055b73b935debadae10d1c06a9b9a0fef33ade606d40d0ff48393e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
